spring.application.name=shrinkly

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/shrinkly
spring.datasource.username=postgres
spring.datasource.password=Archit1604$
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api

snowflake.worker-id=1
snowflake.datacenter-id=1

app.domain=http://localhost:8080